<script>
	window.fbAsyncInit = function() {
		debugger;
		FB.init({appId: '970040746390692', xfbml: true, version: 'v2.4'});
		console.log('initialized!');
	};
	(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {
			return;
		}
		js = d.createElement(s);
		js.id = id;
		js.src = '//connect.facebook.net/en_US/sdk.js';
		fjs.parentNode.insertBefore (js, fjs);
	} (document, 'script', 'facebook-jssdk'));
</script>