<li class='dfe-facebook-login' style='display:none;'>
	<fb:login-button scope='public_profile,email' onlogin='dfeFacebookLogin();'/>
</li>
<?php
// 2015-10-08
// Чтобы кнопка при авторизации не елозила по экрану.
// http://www.question2answer.org/qa/15546/facebook-changed-height-login-button-template-design-breaks?show=15561#a15561
?>
<style>.dfe-facebook-login {width: 50px;  display: inline-block;  margin-right: 15px !important;}</style>
<?php echo \Df\Facebook\I::init();