<?php /** @var \Dfe\FacebookLogin\Block\Login $this */ ?>
<li class='dfe-facebook-login' style='display:none;'>
	<?php
	/**
	 * 2015-10-08
	 * Добавляем «position: fixed;», чтобы кнопка при авторизации не елозила по экрану.
	 * http://stackoverflow.com/a/11452407
	 */
	?>
	<fb:login-button
		scope='public_profile,email'
		onlogin='dfeFacebookLogin();'
	></fb:login-button>
</li>
<style>
	/**
	 * 2015-10-08
	 * Чтобы кнопка при авторизации не елозила по экрану.
	 * http://www.question2answer.org/qa/15546/facebook-changed-height-login-button-template-design-breaks?show=15561#a15561
	 */
	.dfe-facebook-login {
		width: 50px;
		display: inline-block;
		margin-right: 15px !important;
	}
</style>
<?php echo df_facebook_init();

